dmwm/CMSMonitoring

- src/python/CMSMonitoring/Validator.py
As discussed in #8 
- Don't invalidate docs if they contain unknown fields, just issue a warning
- Increase the log level of failed validations to WARNING
> Handling of unknown fields

- src/python/CMSMonitoring/StompAMQ.py
- src/python/CMSMonitoring/Validator.py
- When not choosing a validation schema, the validation now compares all docs to the first one by default (rather than trying out all possible schemas for every document). This will work ok for documents with a very fixed structure, i.e. where the first one is representative, but obviously goes wrong if documents are inhomogeneous or if the first one is a bad example.
- Users can now choose which log level the validation should use to issue feedback. In the same spirit, I removed the `verbose` toggle and replaced it with the log level.
- The validation now always runs on the entire document and collects a list of offending and unknown keys and then returns these. Added options to `make_notification` to drop these from the notification (either or both) and to return them to clients.
> Change 'auto' behavior of validation, validation returns offending/unknown keys

- src/python/CMSMonitoring/datasourcesList.py
- static/datasources.json
Script to generate the grafana datasources list and the current list.
TODO: Next step is to modify monit.py to use the static list to get the datasource type and the table when is not specified.
> Script to generate the grafana datasources list

- doc/logstash/cmsweb.conf
It assumes that if a "cn" starts with a number, is numeric.  It should be a safe assumption (and make the regex much simpler).
> Remove numeric CNs from the dn

- src/python/CMSMonitoring/Validator.py
From https://docs.python.org/3/library/types.html
Types now doesn't include the build-in types. 
"This module defines utility functions to assist in dynamic creation of new types.
It also defines names for some object types that are used by the standard Python interpreter, but not exposed as builtins like int or str are."
> Types is not longer necessary [Python 3][Breaking change]

- bin/monit
- setup.py
- src/python/CMSMonitoring/datasourcesList.py
- src/python/CMSMonitoring/datasources_list.py
- src/python/CMSMonitoring/monit.py
- static/datasources.json
Instead of a dictionary, we want to use the list generated with datasourcesList.py (from the grafana data sources)
This let us to several changes:
- An option to list the data sources
- Instead of the database name, we require the name of the data source in grafana. 
- we can use the type field in the list to determine the type of the query (influxdb/elasticsearch). 
- the python script and the monit bin expect the file to be at the static/datasources.json path (configurable via env var)
(tested using python3)
> Use the external datasources list

- src/python/CMSMonitoring/monit.py
Before this change, if we use a file to load an ES query, and it is a valid multi-query with the index specified, the query will fail (as it was evaluating the filename instead of the file content). 
Also, remove a print from the output. 
Discovered thanks to Bockjoo report https://its.cern.ch/jira/browse/CMSMONIT-130?focusedCommentId=2765441&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-2765441
> Bugfix: File with ES query can have the index

- src/python/CMSMonitoring/StompAMQ.py
_send_signal was failing silently, since no value was returned on the exception
> Added failed notification to _send_single method

- src/python/CMSMonitoring/StompAMQ.py
To prevent the "used before assignment" exception in the exception management.
> [StompAMQ]Initialize the body to None

- doc/training/data_injection.md
The make_notification method now has type as a positional parameter and docId as a keyword argument.
> [Training]add docType to make_notification call

- scripts/es_compare.py
Usage: es_compare.py [OPTIONS] [%Y/%m/%d|%Y-%m-%d|%Y%m%d]
[%Y/%m/%d|%Y-%m-%d|%Y%m%d]
Options:
--es1 TEXT               URL of the original ES
--es2 TEXT               URL of the original ES
--index_prefix TEXT      prefix of the indexes
--credentials_path TEXT  Path for the credentials file,
the credentials
file contains the pair ["username", "password"]
--verbose                Print the ids of the missing documents
--help                   Show this message and exit.
> [ES] Script to compare two Elasticsearch instances in case of migration.

- doc/hdfs/hdfs.json
Adding the condor data from the spider and the SI data injected through AMQ. 
Maybe there are other missing datasets, I've obtained the data for the paper using: 
```bash
hadoop fs -du -s  "/project/monitoring/archive/{cms*,wmagent,wmarchive,toolsandint,training,condor}/*/*/2020/05/14"
```
> Adding some additional folders

- src/go/MONIT/ssb_alerting.go
Fixed :-
- `panic: interface conversion: interface {} is nil, not float64`
- Addition of cycle checking for alerts which have no End Time ( similar to GGUS alerts )
- Addition of checks for all possible variables.
- Addition of check for Start Time > EndTime ( may be a possibility - when an alert dated Nov 2020 is added and deleted afterwards then StartTime becomes greater than time.Now() )
> Fixed ssb_alerting.go

- src/go/MONIT/alert.go
Few points:
1) Severity Level filtering has been added and tested on manually created data. ( Because Severity level tagging for GGUS & SSB yet to be implemented ).
2) Declaration of all possible severity levels in the entire infrastructure is required. As of now, these are severity levels, the integers shows the urgency, used for sorting:-
```
//TODO : Have to add all possibilities of severity levels.
severityLevel["info"] = 0
severityLevel["warning"] = 1
severityLevel["medium"] = 2
severityLevel["high"] = 3
severityLevel["critical"] = 4
severityLevel["urgent"] = 5
```
3) Alerts can be filtered over these three labels ["service", "tag", "severity"]
4) Alerts can be sorted using these four labels ["severity", "starts", "ends", "duration"]
5) Grafana alerts & Prom alerts are also shown.
6) …
> alert CLI Tool added

- src/go/intelligence/int_test/test_cases.json
- src/go/intelligence/int_test/test_config.json
- src/go/intelligence/models/models.go
- src/go/intelligence/pipeline/add_annotations.go
- src/go/intelligence/utils/utils.go
Changes :-
- Change in the config file which now supports annotations based on a different set of keywords to dashboards with a different tag. The list of annotations can be easily configured with a specific set of keywords for specific dashboards identified by tags.
```
"annotationMap": {
"label": "shortDescription",
"annotations": [
{
"actions": ["intervention", "outage"],
"systems": ["network", "database", "db"],
"tags": ["cmsweb-play"]
},
{
"actions": ["update", "upgrade"],
"systems": ["network", "database", "db"],
"tags": ["cmsweb-play2"]
}
],
"urlLabel": "URL"
}
```
- Change in the add_annotation component of the pipeline, where the intersection between the dashboards is found and accordingly they are annotated.
> Int Module - Addition of multiple dashboard annotation based on specific set of keywords

- src/go/MONIT/monit.go
- parseTimes()
- error at day offset, it should be 60\*60\*24
- addAnnotation()
- response body closed, added error handling
- findDashboard()
- the tags were just getting set, but it should be added so that all of the tags can get append in the URL.
> monit.go - minor fixes in parseTimes(), addAnnotation(), findDashboard()

- doc/Rumble/README.md
- Rumble is a querying engine for Hadoop like big data clusters.
- Its query language is JSONiq and Rumble leverages queries to Spark jobs.
- It supports JSON-like datasets including JSON, JSON Lines, Parquet, Avro, SVM, CSV, ROOT as well as text files
> [CMSMONIT-179] Add Rumble documentation

- src/go/MONIT/monit.go
Two solution came to my mind:
1-) [Implemented in this PR] We can keep raw datasources.json in public place of afs or eos. So simple cronjob can work to update datasources.json:
```
curl -k --location --request GET 'https://monit-grafana.cern.ch/api/datasources' \
--header 'Content-Type: application/json' \
--header "Authorization: Bearer $GRAFANA_ADMIN_TOKEN" > /afs/cern.ch/user/c/cuzunogl/public/grafana/datasources.json
```
2-) We can use https://github.com/dmwm/CMSMonitoring/blob/master/static/datasources.json . However, I could not create json struct in go with this json format. I tried json-to-go and jsonutils libraries also, but did not find a solution either. If we use this kind of json structure, we can fetch necessary datasources information from given github path which we keep …
> Edit monit.go such that do not require admin token for queries

- src/go/MONIT/annotationManager.go
fyi @vkuznet 
Bug definition: ID and DASID are concatenated without a space or a tab.
Solution: Removing space in the formatting string is solved the problem
> Bug fix annotationManager.go

- src/go/MONIT/ggus_parser.go
- src/go/MONIT/go.mod
- src/go/MONIT/go.sum
Add provisions to fetch and parse the full description and comments of GGUS tickets in the parser, option enabled via command line flag. Operation is pretty naive, just combing through the HTML response of GGUS since there is no XML or JSON output option for this information. 
PR adds dependency to "golang.org/x/net"
> Add option to fetch detailed descriptions and comments in the ggus parser

- src/go/MONIT/ggus_parser.go
- src/go/MONIT/go.mod
- src/go/MONIT/go.sum
There was a bug where the ticket comment parsing would fail for tickets where there were many comments, as the website would create a nested table and drop-down for the tickets, confusing the scraper. 
New version utilizes goquery for a much more robust parsing process.
> Fix issues with ticket detail parsing on foldable tables

- scripts/ggus_alert.sh
Fix ggus_alerting script parameter.
- I updated `robot-secrets` and `proxy-secrets` in alerts namespace in cmsmonit-new and ha1 (there were old certs, cronjobs also recreated). 
- `proxy-account` ServiceAccount is created in ha1: k apply -f crons/proxy-account.yaml -n alerts
- After this PR, ggus parser will be fixed.
- As a last step, cmsmonit-intelligence pod will be fixed (it fails sometimes), I'm debugging it.
- Yes, I'll improve documentation (adding to my long documentation to-do list :) )
> Fix ggus_alerting parameter

- sqoop/cronjobs.txt
- sqoop/scripts/rucio_ds_daily_stats.sh
- This cron job will dump following tables for the need of sending rucio datasets info to ES task:
- `FILES, DATASETS, DATA_TIERS, PHYSICS_GROUPS, ACQUISITION_ERAS, DATASET_ACCESS_TYPES` tables from DBS 
-   and `REPLICAS, CONTENTS` tables from Rucio.
- Since Rucio and DBS oracle instances are separate, dumps will run parallel imports from DBS and Rucio.
- Total dumping time is ~25 minutes for ALL above tables. Total size of all above tables is ~20GB (see example `/tmp/cmssqoop/rucio_daily_stats-2022-03-31`)
- Todays dumps will be deleted in the next run (next day).
Ref: CMSMONIT-450
fyi @leggerf @brij01
> Add sqoop job for rucio and dbs datasets daily stats

- .gitignore
- src/python/CMSMonitoring/StompAMQ7.py
- src/python/CMSMonitoring/__init__.py
- src/python/requirements.txt
This PR implements a new class to support stomp v6.1.1-v7.0.0 versions: `from CMSMonitoring.StompAMQ7 import StompAMQ7`
Backward compatible. `StompAMQ` class is not changed and can be used by stomp v4.1.21 version.
We're currently not supporting older versions like v3.
**Reason:**
There are changes in new versions of [Stomp.py](https://github.com/jasonrbriggs/stomp.py) library . Latest [pypi/CMSMonitoring](https://pypi.org/project/CMSMonitoring/) release uses 4.1.21. 
**Changes:**
Since v6.1.1, mainly they changed: 
- listener function parameters. body, headers -> frame
- conn.start() function is removed
- running conn.disconnect() immediately after sending data gives `application data after close notify (_ssl.c:2428)` SSL error. Community does not have a solution yet and it seems it's …
> Implement new StompAMQ7 for v7

- .github/workflows/build-go-tools.yml
- .github/workflows/build-rucio-mon.yml
We're not ready to use `build-push-action@v3` version, since we're fetching Dockerfile from remote and apply `sed` on it. `@v3` we can provide `file` option along with `build-args` and we can modify our Dockerfiles to use build args, but I could not find how to wget Dockerfile from other git repo in [@v3 docs](https://github.com/docker/build-push-action). Anyway, I'm switching to `@v1`.
> Fix gh workflow

- .github/workflows/build-nats.yml
- README.md
- Created new gh action `build-nats.yml` for `cmsmonitoring/nats-sub` docker image build.
- Changed the tag of `cmsmon-rucio-ds-web` from `go-` to `rgo-`
> Add nats-sub dcoker image gh action

- .github/workflows/build-py.yml
- src/python/requirements.txt
- src/python/setup.py
This is a fix for pypi release gh workflow. `setup` of `distutils.core` is deprecated in python version `3.10`, that's why release failed. 
Now it is migrated to `setuptools.setup` with some refactoring.
I am merging this PR for other waiting tasks, please comment even though it is merged.
> Fix github workflow for py tag

- src/python/CMSMonitoring/StompAMQ7.py
As suggested by the messaging team, heartbeat[1] is implemented in `StompAMQ7` module. Instead of using tuple, I make this setting compatible with its Go version[2] and use `send_timeout, recv_timeout` parameters. Default heartbeat timeouts are `4000ms` for recv and send.
New release is published from this commit: https://pypi.org/project/CMSMonitoring/0.6.5/
Example run:
`pip install CMSMonitoring==0.6.5`
```
from CMSMonitoring.StompAMQ7 import StompAMQ7
stompSvc = StompAMQ7(username=username, password=password, producer=producer, topic=topic, key=ckey, cert=cert, validation_schema=None, host_and_ports=[(host, port)], send_timeout=4000, recv_timeout=4000)
messages = []
doc = {"wmbs_status": "ceyhun_4", "type": "test_ceyhun", "num_jobs":0, "agent_url": "test_ceyhun_4"}
notif, _, _ = …
```
> Add send and receive hearbeat params to stomp

- src/python/CMSMonitoring/StompAMQ.py
- src/python/CMSMonitoring/StompAMQ7.py
Fixes #160 
Check if a logger object has been passed over to StompAMQ modules before making any changes to it. If one already exists, use it as is without changing the format of the log records.
@mrceyhun could you please review and release this PR. If everything looks fine, I would need a new tag with these changes in.
> Avoid overwritting logger object in StompAMQ modules

- src/go/rucio-dataset-monitoring/static/templates/datasets.tmpl
- src/go/rucio-dataset-monitoring/static/templates/detailed_datasets.tmpl
As requested by our users, new page length options are added `500, 1000, 10000` for "RUCIO DATASETS MONITORING" in http://cmsweb-test1.cern.ch:31280/ . So, max page length option will be `10000`.
> Increase page length limit

- src/python/CMSMonitoring/StompAMQ7.py
Workaround for https://github.com/dmwm/WMCore/issues/11281
However, tomorrow I am going to suggest a PR upstream to the stomp.py project. So I suggest not to merge these changes until we can hear from the stomp.py developers.
> Make stomp.py less verbose

- src/python/CMSMonitoring/StompAMQ7.py
Fix for #166 
Testing took my time. stomp.py still has problems in v8+. In v7.0.0, if we use certificates for authentication, stomp.py produces `ssl EOF occurred in violation of protocol` error on final disconnect. In v8+, even worse, connection does not established with the AMQ broker. I could not find a solution for that and it is more of a certificate problem AFAIK from the community. Anyway, this should work for user/pass auth and it will disconnect after each send().
@amaltaro sorry for the trouble, hope this works! I will be around if you apply this patch today.
> Add disconnect to StompAMQ7

- grafana-backup/README.md
- grafana-backup/dashboard-exporter.py
- grafana-backup/run.sh
CMSMONIT-531
We are moving cmsmonitoringbackup job from to Kubernetes cluster. For this a few changes are needed:
* code needs to be transferred to CMSMonitoring repository (therefore GitLab to GitHub)
* it will be using cmsmon-spark docker [image](https://github.com/dmwm/CMSKubernetes/tree/master/docker/cmsmon-spark) from the Kubernetes so the image needs to be updated accordingly
* authentication and alerting in run.sh needs to be changed as well so that it would work from Kubernetes
> Move cmsmonitoringbackup Kubernetes cluster

- sqoop/configs-dev.json
- sqoop/configs.json
- sqoop/cronjobs.txt
- sqoop/curator/hdfs_cleaner.sh
- sqoop/scripts/cms-tasks.sh
CMSMONIT-549
Daily dump of `CMS_ANALYSIS_REQMGR.TASKS` table that will be run on `cron` Kubernetes cluster:
- finished dump script
- updated configs
- updated HDFS cleaner script so that it would delete old dumps of this table
Another small PR incoming in the CMSKubernetes repository regarding this.
FYI @leggerf @brij01 @novicecpp
> Tasks dump with sqoop

- .github/workflows/build-go-tools.yml
We got an issue on our previous release (see https://github.com/cms-sw/cmsdist/pull/8682#issuecomment-1711731431).
Therefore, here is a fix suggested by @vkuznet:
> to fix this issue you should change CI/CD workflow files which build go tools to
> build their static executable.
> ```
> go build -o monit monit.go
> ```
> This command by default builds shared version of the executable. To make static
> version you should change it to
> ```
> go build -o monit monit.go -s -w -extldflags -static
> ```
> Then, the new executable will no longer depends on specific GLIBC version.
> Update monit tools GH pipeline

- .github/workflows/build-go-tools.yml
After the build [workflow](https://github.com/dmwm/CMSMonitoring/actions/runs/6156256171) from the previous [PR](https://github.com/dmwm/CMSMonitoring/pull/238) failed, syntax of the command had to be changed. See [this article](https://mt165.co.uk/blog/static-link-go/) about that.
FYI @vkuznet @leggerf @brij01
> Change the syntax of go command

- .github/workflows/build-go-tools.yml
Update builds in the GitHub workflows because I have noticed that the other executables also don't work on `lxplus8`.
FYI @vkuznet @leggerf @brij01
> Make other executables static

- sqoop/curator/hdfs_cleaner.sh
- sqoop/scripts/rucio_table_dumps.sh
@amanrique1 wants to have new tables (`BAD_REPLICAS` and  `DELETED_DIDS`) for the daily sqoop rucio dump from Oracle to HDFS.
> Update sqoop rucio_table_dumps.sh

- src/python/CMSMonitoring/datasources_list.py
- static/datasources.json
Users are often asking what some data source in Grafana corresponds to in OpenSearch, but this file was lacking the information about the actual URL. This update should fix this.
@leggerf @brij01
> Add url to datasources file

- cpueff-goweb/spark/cpueff_stepchain_goweb.py
CMSMONIT-599
- Main fix: adding line 248 to check whether `task` is not null. This caused all of the problems showing an error message `TypeError: 'NoneType' object is not iterable`
- Added some additional checks for the null values
- Reformatted file with [`black`](https://black.readthedocs.io/en/stable/) tool
> Fix CPU efficiency NoneType error

- cpueff-goweb/static/templates/condor_detailed.tmpl
- cpueff-goweb/static/templates/condor_main.tmpl
- cpueff-goweb/static/templates/condor_row_site_detailed.tmpl
CMSMONIT-611
Change `Non Eviction Eff` column name to `Badput` and add a description of it.
> Add Badput description

- src/python/requirements.txt
We found incompatibilities of `jsonschema` python package used by rucio and CMS Monitoring. The rucio requires version `jsonschema>=4.20.0` while here we still used `jsonschema~=3.2.0`. Because of this conflict the WM stack cannot be upgraded as it depends both on CMSMonitoring and rucio clients. To align the `jsonschema` version I provide here the upgrade of its dependencies to align with rucio clients.
FYI: @amaltaro
> Upgrade jsonschema package as it is not compatible with one used by rucio
