dmwm/CMSMonitoring

schemas/ClassAds.json
see e.g.:
https://docs.google.com/spreadsheets/d/1x73SxboZqNvpYKHmaJ9PioT3itpw4qQrTjUecnKLTi4/edit#gid=0
=> add Analysis to JobType

jsonschemas/JobMonitoring.schema, schemas/JobMonitoring.json
Fixing types in two fields (causes invalid type in the validation).
=> [Schemas][JobMonitoring] Making the floats explicit

schemas/ClassAds.json
In case there is no primary or secondary input, we need to set a proper value to their location (which is none, since there is no data). 
Let me know if you rather have another value or another way to handle it
FYI @belforte
=> Set data location to None when there is no data

src/python/CMSMonitoring/StompAMQ.py, src/python/CMSMonitoring/Validator.py, test/test_brokers.py
=> Consolidate logging/logger usage; satisfy to pylint suggestions

scripts/sourcesCompare.sh
This script will assert that the number of jobs in each state is consistent between ES and Influxdb, and the completed jobs are consistent with es-cms.
=> Script to validate condor data in monit

scripts/cronPopularityPlot.sh, src/python/CMSMonitoring/scrutiny_plot.py
A small change and the cronjob script that creates the symlink to the plot. 
The python script will output the path of the file, and the bash script will use it to create/update the link. 
I also removed the cache step from the spark workflow as it is not helpful in this context.
=> Changes to create/update the symlink for the latest plot.

doc/training/data_injection.md
Change the path of the certificates, use https in the git clone, and some formatting changes.
=> Data Ingestion Training: Some changes to make it more straightforward

doc/training/data_injection.md
The virtualenv will be python 2 as in the vocms092 machine there is not python3 yet.
=> Tutorial: Add instructions to create a virtualenv

doc/training/data_injection.md
Changing the route to the credentials (to the cmsmonit afs) and adding instructions to check the HDFS data
=> Training: credentials and data in HDFS

src/go/MONIT/alerting.go
Implementation of alerting tool for the CERN SSB status board queries which will take it's data and inject alerts into AlertManager.
=> Alerting Tool

scripts/ggus_alert.sh, scripts/ggus_alert_manage, src/go/MONIT/ggus_alerting.go, src/go/MONIT/ssb_alerting.go
Implementation of alerting tool for the GGUS Ticketing System which will ingest JSON data and inject them into AlertManager. Ending Time for each alerts has been implemented on the logic of checking if a particular ticket has been resolved or not, and updating the same in AlertManager.
=> Added ggus_alerting files, updated ssb_alerting files

scripts/ggus_alert_manage
=> Updated ggus_alert_manage

scripts/ggus_alert.sh, scripts/ggus_alert_manage
=> Updated ggus_alert_manage+ggus_alert.sh

scripts/ssb_alert.sh, scripts/ssb_alert_manage
=> Updated ssb_alert_manage+ssb_alert.sh

src/go/MONIT/ggus_alerting.go, src/go/MONIT/ggus_parser.go
Fixed CSV & XML Parsing issue in ggus_parser.
=> Fixed CSV & XML Parsing issue in ggus_parser

src/go/MONIT/ssb_alerting.go
More Labels have been added which will help in better visualization.
=> More Labels added to ssb_alerting

src/go/MONIT/ggus_alerting.go
More Labels have been added which will help in better visualization.
=> More Labels added to ggus_alerting

src/go/MONIT/intelligence.go
- added regex matching
- added both ["," , " "] seperator
- also configured seperator in case new seperator is introduced
=> updated intelligence.go added regex matching, configured seperator

src/go/MONIT/ssb_alerting.go
updated the default severity level value
- severity = "notification"
=> update ssb_alerting default severity value

doc/scripts/GrafanaDuplicator.md, doc/scripts/GrafanaTextPropagation.md, src/python/CMSMonitoring/grafana_duplicator.py, src/python/CMSMonitoring/grafana_manager.py, src/python/CMSMonitoring/grafana_textpanel_propagation.py
It can use an *uid* or a *query* expression to select the dashboards to copy, creates the documents to create new dashboards, changing the title and replacing the datasources if needed (in all panels and variables). 
It's a draft because it needs some additional testing and documentation.
=> Grafana duplicator

src/go/intelligence/README.md, src/go/intelligence/main.go, src/go/intelligence/models/models.go, src/go/intelligence/pipeline/add_annotations.go, src/go/intelligence/pipeline/delete_old_silents.go, src/go/intelligence/pipeline/fetch_alert.go, src/go/intelligence/pipeline/keyword_matching.go, src/go/intelligence/pipeline/ml_box.go, src/go/intelligence/pipeline/preprocess.go, src/go/intelligence/pipeline/push_alert.go, src/go/intelligence/pipeline/silence_alert.go, src/go/intelligence/utils/utils.go
Changes Made
- Race condition on Maps handled.
- Deletion of Expired Silences when original Alerts are resolved. 
- Proper handling of suppressed alerts.
=> Race Condn elimination, Deletion of Silences, Proper handling of Suppressed Alerts

src/go/MONIT/alert.go
dropping redundant -details flag.
=> alert CLI tool detail printing of alert modification

src/go/intelligence/models/models.go, src/go/intelligence/pipeline/add_annotations.go, src/go/intelligence/test/test.go
- AM Persistance issue fixed
- Annotation process code refactoring
=> Intelligence module - Testing script fixes 

src/go/intelligence/test/Dockerfile, src/go/intelligence/test/test_config.json, src/go/intelligence/test/test_wrapper.sh
- runs AM inside the container.
- pushes fake alerts
- annotates the Grafana dashboards
- outputs the testing result
=> Intelligence module - Testing script Dockerfile

doc/AlertManagement/README.md, src/go/intelligence/README.md
- Added LXplus User Environment setup prior to run/test setup of intelligence module.
- Moved intelligence module.details to /doc/AlertManagement in order to separate installation documentations.
=> Documentation update

scripts/ggus_alert.sh, scripts/ggus_alert_manage, scripts/ssb_alert.sh, scripts/ssb_alert_manage
Alerting Services (GGUS & SSB) had few changes done by @vkuznet in few scripts for the data_file field. But it was not updated.
@vkuznet Please review and Merge.
=> Minor fixes in accordance for the latest versions

doc/AlertManagement/installation.md
AlertManagement doc addition of required package download instruction for alerting services/fixes
=> Documentation - package download addition

src/go/MONIT/annotationManager.go
- Lists all annotations.
- Lists all annotations with specified tags.
- Lists all annotations over some time period.
- Deletes listed annotations.
```
Usage: annotationManager [options]
-action string
Action to be performed. [list, create, delete, deleteall, update] Default: list
-annotation string
Annotation text
-annotationID int
Annotation ID required in making delete api call for deleting an annotation
-generateConfig
Flag for generating default config
-tags string
List of tags seperated by comma
-token string
Authentication token to use (Optional-can be stored in config file)
-trange string
Time Range for filtering annotations.
-verbose int
verbosity level, can be overwritten in config (Optional-can be stored in config file)
Environments:
CONFIG_PATH:	 Config to use, default …
```
=> annotationManager added

doc/Rumble/README.md, doc/Rumble/ex1.jq, doc/Rumble/ex2.jq, doc/Rumble/ex3.jq, scripts/run_rumble.sh, src/go/Rumble/rumble.go, src/python/Rumble/rumble.ipynb, src/python/Rumble/rumble.py
@vkuznet 
Rumble related non-k8s related files moved to CMSMonitoring.
=> Move rumble files to CMSMonit from CMSKubernetes

src/go/MONIT/monit.go
Provided [DEBUG] tag for error and log messages when verbosity 2 is given.
Added some explanation messages for users.
=> Provide better error messages for users

src/go/Rumble/rumble.go, src/python/Rumble/rumble.ipynb, src/python/Rumble/rumble.py
@vkuznet 
I added the port of rumble server to host.
=> Edit default server host and bug fix

src/go/MONIT/annotationManager.go
Added dashboardId filter provided by Grafana annotations API in annotationManager.go tool
@vkuznet
=> Added dashboardId filter provided by Grafana annotations API in annotationManager.go tool

static/datasources.json
@vkuznet 
Created using monit go:
/cvmfs/cms.cern.ch/cmsmon/monit -token $GRAFANA_ADMIN_TOKEN -writedsto static/datasources.json
=> Update grafana data sources

src/python/CMSMonitoring/hs06corehr.py
=> [CMSMONIT-321] Add hs06corehr.py script

src/go/MONIT/ggus_alerting.go, src/go/MONIT/ssb_alerting.go
Updated ssb_alerting.go and ggus_alerting.go scripts to be compatible with multiple instances of alertmanager
=> Updated ssb_alerting.go and ggus_alerting.go scripts

src/python/CMSMonitoring/grafana_manager.py, src/python/CMSMonitoring/grafana_textpanel_propagation.py
=> Edit scripts which modify cmsmonit home panels

scripts/eos_path_size.sh, src/python/CMSMonitoring/eos_path_size.py
I'll add this script as acronjob to cmsmonit.
=> Implement acronjob for eos path sizes

src/python/CMSMonitoring/eos_path_size.py
@vkuznet  Hope this will be the last request from our users about this issue.
=> Fix eos path size

tools/testing-logstash/README.md, tools/testing-logstash/docker/Dockerfile, tools/testing-logstash/docker/bashrc_extension, tools/testing-logstash/docker/depracated_server.sh, tools/testing-logstash/docker/logstash.repo, tools/testing-logstash/docker/server.py, tools/testing-logstash/examples/logstash-ex1.conf, tools/testing-logstash/examples/logstash-ex2.conf, tools/testing-logstash/logstash.yaml
Add easy logstash testing in Kubernetes to CMSMonitoring repo.
=> Add testing-logstash in kubernetes

.gitignore, scripts/eos_path_size.sh, src/python/CMSMonitoring/eos_path_size.py
=> Improve eos path size html

src/python/CMSMonitoring/eos_path_size.py
=> Edit eos path size

scripts/cronPopularityPlot.sh, scripts/eos_path_size.sh, src/python/CMSMonitoring/eos_path_size.py
=> Modify and improve EOS quota page

scripts/eos_path_size.sh, src/html/eos_path_size/main.html, src/python/CMSMonitoring/eos_path_size.py
=> Add url param and refactor eos path size page

src/html/eos_path_size/main.html, src/python/CMSMonitoring/eos_path_size.py
=> Polish html

scripts/cron4rucio_quotas.sh, src/html/rucio_quotas/htmltemplate.html, src/python/CMSMonitoring/rucio_quotas.py
Moving the cron job of Garyfallia and Benedikt to cmsmon acrontab.
usercert and userkey(from secrets/robot which are cmsmonit user's certs) are added to ./globus directory in `cmsmonit` user's lxplus for `voms-porxy-init`.
=> Add rucio quotas cron of benedikt

scripts/cron4rucio_quotas.sh
To not get email even when the hourly acronjob is successful
=> Silence noisy stdout of rucio_quotas

src/python/CMSMonitoring/StompAMQ7.py
=> Fix empty metadata check

.github/workflows/build-cmsmon-rucio-mon-goweb.yml
Rename `cmsmon-rucio-ds-web` to `cmsmon-rucio-mon-goweb`
=> Rename docker file name in GH workflow

scripts/eos_path_size.sh, src/html/eos_path_size/main.html, src/python/CMSMonitoring/eos_path_size.py
=> Implement new eos quotas page with ec and non ec tables

sqoop/scripts/dbs3_full_global.sh
Run small table dumps in parallel and big ones in order. Couple of other fixes too..
=> Fix num_mappers bash list operation

src/python/requirements.txt
Ref https://github.com/dmwm/CMSMonitoring/issues/178
=> Downgrade jsonschema to 3.2 to be able match rucio-clients

rucio-dataset-monitoring/spark/createindexes.js, rucio-dataset-monitoring/spark/cron4rucio_hdfs2mongo.sh, rucio-dataset-monitoring/spark/cron4rucio_spark2hdfs.sh, rucio-dataset-monitoring/spark/rucio_all_datasets.py, rucio-dataset-monitoring/spark/rucio_all_detailed_datasets.py, rucio-dataset-monitoring/spark/utils.sh
Gathering all rucio-dataset-monitoring related codes in single directory makes sense for future development. CMSSpark codes are moved to here under spark directory. Ref https://github.com/dmwm/CMSSpark/pull/139
=> Move dataset monitoring spark scripts to CMSMonitoring

rucio-dataset-monitoring/config.json, rucio-dataset-monitoring/controllers/pages.go, rucio-dataset-monitoring/server/config.go, rucio-dataset-monitoring/server/server.go, rucio-dataset-monitoring/spark/rucio_all_datasets.py, rucio-dataset-monitoring/spark/rucio_all_detailed_datasets.py, rucio-dataset-monitoring/static/js/datasets.js, rucio-dataset-monitoring/static/templates/datasets.tmpl
In config.json, someone can set `"base_endpoint": "main",` to use as base endpoint. I set `main` for now. So our page changed to https://cms-dm-monitoring.cern.ch/main/
=> Fix replicas STATE=A and implement base root endpoint for web service

src/python/CMSMonitoring/StompAMQ7.py
**Bug Description**: If `metadata` dict is provided in `make_notifications` function; in second `make_notification` call, `metadata` includes all StompAMQ7 added fields(producer, type, _id, doc_type) from the first call. Because, Python passes dict variables by reference and second metadata is updated version of client's metadata.
**Fix**: Fixed by always creating a `my_metadata = {}` variable and later update it with client's metadata.
**Effect**: No expected effect or breaking change in clients. Even a client encountered this bug, "MONIT reserved key" check has been protecting the misconfigured data send.
=> Fix stompamq7 metadata dict pass by ref issue because of same var name

src/html/openstack_accounting/main.html, src/python/CMSMonitoring/openstack_accounting.py
=> Make columns hidden default and polish eos openstack page

scripts/utils.sh, src/python/CMSMonitoring/eos_path_size.py, src/python/CMSMonitoring/openstack_accounting.py
Couple of fixes in scripts including silencing curl.
=> Improve CMSMonitoring cron scripts, silence curl, fix py w+

src/python/CMSMonitoring/openstack_accounting.py
TOTAL row will be first row and this will not change with different ordering.
=> Fix total row to top in eos openstack page

src/html/openstack_accounting/main.html, src/python/CMSMonitoring/openstack_accounting.py
Hello, I added a new `key:value` to the JSON: it is the `contacts` key
=> Adds Contacts column to Openstack accounting

src/html/openstack_accounting/main.html, src/python/CMSMonitoring/openstack_accounting.py
=> Fix eos openstack html page

sqoop/scripts/rucio_table_dumps.sh
By request from Andres Manrique Ardila
=> Add to sqoop, rucio tables of requests_history subscriptions dumps

cpueff-goweb/spark/cron4cpueff_goweb.sh, rucio-dataset-monitoring/spark/cron4rucio_spark2hdfs.sh
=> Fix shuffle issue w/ spark.shuffle.useOldFetchProtocol=true in sparks

grafana-backup/dashboard-exporter.py
Kubernetes has strict rules for the reading of secrets, so I am updating this...
=> Another permissions fix

src/python/CMSMonitoring/openstack_accounting.py
We are constantly the same error because of this and it doesn't seem that the root cause is going to be solved (CMSVOC-459), so this will at least reduce the noise.
FYI @leggerf
=> Add new exception to json file load

.github/workflows/build-go-tools.yml
Pipeline update to build static executable for monit tool
=> Another pipeline update

scripts/cron4rucio_quotas.sh
Should fix this issue https://github.com/cms-sw/cmsdist/issues/8739#issuecomment-1754792109
=> Update rucio quotas script

grafana-backup/README.md, grafana-backup/dashboard-exporter.py, grafana-backup/run.sh
Although it was decided that the conversion to Go is not worth it (see https://github.com/dmwm/CMSMonitoring/pull/244), current Python script could still be improved. Changes:
- refactored and reformatted Python code
- removed backup to HDFS step (as discussed on CMSMONIT-551)
=> Update dashboard exporter

rucio-dataset-monitoring/spark/cron4rucio_hdfs2mongo.sh
Switching from the custom MongoDB instance also requires slightly changing the import job command line configs
=> Change rucio dm mon mongodb import configs

rucio-dataset-monitoring/spark/cron4rucio_hdfs2mongo.sh
Reverts dmwm/CMSMonitoring#260
We couldn't achieve the same performance with the common cmsweb MongoDB, so I am returning to the custom MongoDB instance running as a side-container. Related JIRA ticket - `CMSMONIT-516`.
=> Revert "Change rucio dm mon mongodb import configs"

static/datasources.json
Update data sources list after the change of OpenSearch aliases
=> Update datasources json

src/python/CMSMonitoring/datasources_list.py, static/datasources.json
Update `datasources_list.py` script so that the index/databse would be shown more correctly and update the `datasources.json` accordingly
=> Update datasources script and list

sqoop/run.sh, sqoop/scripts/cms-aso.sh, sqoop/scripts/cms-dbs3-blocks.sh, sqoop/scripts/cms-dbs3-datasets.sh, sqoop/scripts/cms-dbs3-files.sh, sqoop/scripts/cms-tasks.sh, sqoop/scripts/dbs3_full_global.sh, sqoop/scripts/rucio_table_dumps.sh, sqoop/scripts/sqoop_utils.sh
- Java path part is fixed in the Dockerfile https://github.com/dmwm/CMSKubernetes/blob/master/docker/sqoop/Dockerfile#L42-L43
- fixing amtool alert format for the new version
=> Adjust sqoop scripts to use alma9 and spark3
